# Generated by Django 5.0.2 on 2024-02-27 21:29

from django.db import migrations, models  # Importa módulos necessários para migrações e definição de modelos


class Migration(migrations.Migration):

    # Indica que esta é a migração inicial para o app
    initial = True

    # Define que não há dependências para esta migração
    dependencies = []

    # Define as operações que serão realizadas por esta migração
    operations = [
        # Cria o modelo 'Category'
        migrations.CreateModel(
            name="Category",
            fields=[
                # Campo 'id' como chave primária
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                # Campo 'title' para o título da categoria
                ("title", models.CharField(max_length=100)),
                # Campo 'slug' para o slug da categoria, deve ser único
                ("slug", models.SlugField(unique=True)),
                # Campo 'description' para a descrição da categoria, pode ser vazio ou nulo
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                # Campo 'active' para indicar se a categoria está ativa, padrão é True
                ("active", models.BooleanField(default=True)),
            ],
        ),
        # Cria o modelo 'Product'
        migrations.CreateModel(
            name="Product",
            fields=[
                # Campo 'id' como chave primária
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                # Campo 'title' para o título do produto
                ("title", models.CharField(max_length=100)),
                # Campo 'description' para a descrição do produto, pode ser vazio ou nulo
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                # Campo 'price' para o preço do produto, deve ser um inteiro positivo
                ("price", models.PositiveIntegerField(null=True)),
                # Campo 'active' para indicar se o produto está ativo, padrão é True
                ("active", models.BooleanField(default=True)),
                # Campo 'category' para associar o produto a múltiplas categorias, pode ser vazio
                ("category", models.ManyToManyField(blank=True, to="product.category")),
            ],
        ),
    ]
