# Generated by Django 5.0.2 on 2024-02-27 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # Indica que esta é a migração inicial para o app
    initial = True

    # Define as dependências desta migração
    dependencies = [
        ("product", "0001_initial"),  # Depende da migração inicial do app 'product'
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # Depende do modelo de usuário configurável
    ]

    # Define as operações que serão realizadas por esta migração
    operations = [
        # Cria o modelo 'Order'
        migrations.CreateModel(
            name="Order",
            fields=[
                # Campo 'id' como chave primária
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                # Campo 'product' como relação ManyToMany com o modelo 'Product'
                ("product", models.ManyToManyField(to="product.product")),
                # Campo 'user' como ForeignKey para o modelo de usuário configurável
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,  # Deleta as ordens associadas quando o usuário é deletado
                        to=settings.AUTH_USER_MODEL,  # Referencia o modelo de usuário configurável
                    ),
                ),
            ],
        ),
    ]
